#!/bin/bash -xe
. ../devenv/env.sh
WORKDIR_NOINSTR=../musl-noinstr
WORKDIR_INSTR=../musl-instr
WORKDIR_FULLINSTR=../musl-fullinstr

MUSL_P2ALIGN=0 CFLAGS=$CFLAGS_NOINSTR WORKDIR=$WORKDIR_NOINSTR ./build-one.sh
MUSL_P2ALIGN=4 CFLAGS=$CFLAGS_INSTR WORKDIR=$WORKDIR_INSTR ./build-one.sh
MUSL_P2ALIGN=5 CFLAGS=$CFLAGS_FULLINSTR WORKDIR=$WORKDIR_FULLINSTR ./build-one.sh
